services:
  - type: web
    name: gym-backend
    rootDir: backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true

  - type: static
    name: gym-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: build
    autoDeploy: true
